language: rust
cache: cargo
sudo: false
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of coveralls
      - libiberty-dev # same
rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        # upload the documentation
        sh scripts/travis-doc-upload.sh
      fi
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        # measure code coverage and upload to coveralls.io (the verify
        # argument mitigates kcov crashes due to malformed debuginfo, at the
        # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
        travis-cargo coveralls --no-sudo --verify
        set -v -x
        for f in target/debug/test_assembler-*; do
          ./kcov/build/src/kcov --verify --exclude-pattern=/.cargo --include-pattern=$PWD target/kcov $f
        done
        # Workaround for https://github.com/huonw/travis-cargo/issues/58
        ./kcov/build/src/kcov --merge --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo --include-pattern=$PWD target/kcov target/kcov
        set +v +x
      fi

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
